services:
  auth-db:
    container_name: auth-db
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data

  subscription-db:
    container_name: subscription-db
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subscription_db
    ports:
      - "5434:5432"
    volumes:
      - subscription-db-data:/var/lib/postgresql/data
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  auth-db-data:
  subscription-db-data: