server:
  port: 8080

spring:
  application:
    name: lightsub-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: auth-service
              uri: lb://lightsub-auth-service
              predicates:
                - Path=/auth/**
            - id: subscription-service
              uri: lb://lightsub-subscription-service
              predicates:
                - Path=/subscriptions/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

security:
  jwt:
    secret: ${JWT_SECRET}
